// Leetcode Problem: 38. Count and Say
// Link: https://leetcode.com/problems/count-and-say/
// Difficulty: Medium
// Tags: String, Recursion

// ✅ Approach:
// Use Recursion to build the sequence.
// The idea is:
//  - The current term is generated by "saying" the previous term.
//  - We recursively compute countAndSay(n-1)
//  - Then read the string and count consecutive characters
//  - Append the count followed by the character to form the result
//
// Example:
// n = 4
// "1" → "11" → "21" → "1211"

class Solution {
public:
    string countAndSay(int n) {

        // Base Case:
        // The first term of the sequence is always "1"
        if(n == 1)
            return "1";

        // 🔹 Recursive call to get the previous sequence
        string say = countAndSay(n - 1);
        string res;  // Stores the current sequence

        int len = say.length();

        // Traverse the previous string
        for(int i = 0; i < len; i++) {

            char curr_ch = say[i];  // Current character
            int count = 1;          // Count of consecutive characters

            // Count how many times the current character repeats
            while(i + 1 < len && say[i] == say[i + 1]) {
                count++;
                i++;  // Move to the next character
            }

            // Append count and character to result
            res += to_string(count) + string(1, curr_ch);
        }

        // Return the generated sequence for nth term
        return res;
    }
};